name: bonsoir_linux
description: Linux implementation of the Bonsoir plugin.
homepage: https://bonsoir.skyost.eu
repository: https://github.com/Skyost/Bonsoir/tree/master/packages/bonsoir_linux
issue_tracker: https://github.com/Skyost/Bonsoir/issues
version: 5.0.1

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.7.0"

flutter:
  plugin:
    implements: bonsoir
    platforms:
      linux:
        dartPluginClass: BonsoirLinux

dependencies:
  flutter:
    sdk: flutter
  bonsoir_platform_interface: ^5.0.0
  dbus: ^0.7.10
  meta: ^1.8.0

dev_dependencies:
  flutter_lints: ^3.0.1

dependency_overrides:
  bonsoir_platform_interface:
    path: ../bonsoir_platform_interface/
