name: bonsoir_android
description: Android implementation of the Bonsoir plugin.
repository: https://github.com/Skyost/Bonsoir/tree/master/packages/bonsoir_android
issue_tracker: https://github.com/Skyost/Bonsoir/issues
version: 4.1.2

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.7.0"

flutter:
  plugin:
    implements: bonsoir
    platforms:
      android:
        package: fr.skyost.bonsoir
        pluginClass: BonsoirPlugin

dependencies:
  flutter:
    sdk: flutter
  bonsoir_platform_interface: ^4.1.2

dependency_overrides:
  bonsoir_platform_interface:
    path: ../bonsoir_platform_interface/
