name: bonsoir_windows
description: Windows implementation of the Bonsoir plugin.
homepage: https://bonsoir.skyost.eu
repository: https://github.com/Skyost/Bonsoir/tree/master/packages/bonsoir_windows
issue_tracker: https://github.com/Skyost/Bonsoir/issues
version: 5.1.3

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.7.0"

flutter:
  plugin:
    implements: bonsoir
    platforms:
      windows:
        pluginClass: BonsoirWindowsPluginCApi

dependencies:
  flutter:
    sdk: flutter
  bonsoir_platform_interface: ^5.1.1

dependency_overrides:
  bonsoir_platform_interface:
    path: ../bonsoir_platform_interface/
